apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
  namespace: retail-app
  labels:
    Project: karatu-2025-capstone
data:
  RETAIL_UI_ENDPOINTS_CATALOG:  http://catalog:80
  RETAIL_UI_ENDPOINTS_CARTS:    http://carts:80
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout:80
  RETAIL_UI_ENDPOINTS_ORDERS:   http://orders:80
