apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: retail-app
  labels:
    app: ui
    Project: karatu-2025-capstone
spec:
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
