apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts
  namespace: retail-app
  labels:
    Project: karatu-2025-capstone
  annotations:
    eks.amazonaws.com/role-arn: "REPLACE_WITH_CARTS_IRSA_ROLE_ARN"
